### ISSUE TITLE
FreeCAD fails to open OpenSCAD files.

### ISSUE THREAD

**Issue by felixknollmann** [FreeCAD/FreeCAD-Bundle#111]
When opening a OpenSCAD file I get the following error:
16:27:03  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\FreeCAD 0.19\Mod\OpenSCAD\importCSG.py", line 119, in open
    processcsg(tmpfile)
  File "C:\Program Files\FreeCAD 0.19\Mod\OpenSCAD\importCSG.py", line 177, in processcsg
    result = parser.parse(f.read())
  File "C:\Program Files\FreeCAD 0.19\bin\lib\site-packages\ply\yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "C:\Program Files\FreeCAD 0.19\bin\lib\site-packages\ply\yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "C:\Program Files\FreeCAD 0.19\Mod\OpenSCAD\importCSG.py", line 854, in p_multmatrix_action
    parentcolor=p[6][0].ViewObject.ShapeColor
<class 'IndexError'>: list index out of range

Instead of opening the part with all subsections, it just makes a single cube.

**Comment by chennes** [comment]
Can you please attach the OpenSCAD file that's failing for you? Alternately, test it again using the 0.20 development branch -- we've done a lot of work on OpenSCAD compatibility since 0.19 was released.
