### ISSUE TITLE
[Issue] Program received signal SIGSEGV at startup (Debian testing, python 3.11.1, Qt 5.15.7)

### ISSUE THREAD

**Issue by marcogiusti** [FreeCAD/FreeCAD-Bundle#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
FreeCAD 0.20.1, Libs: 0.20.1R (Debian testing package)

and

FreeCAD 0.20.1 Revision: 29410 (Git) (latest AppImage)
```

### Subproject(s) affected?

None

### Issue description

FreeCAD work fine until I plug/unplug an external monitor. After I do this I cannot start FreeCAD unless I reboot. I use [mons](https://github.com/Ventto/mons) to easily control xrandr.

The stacktrace using the debian package, when using the AppImage the output is similar:

```
$ freecad
FreeCAD 0.20.1, Libs: 0.20.1R
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2022
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####
  #                    #      # #   #   #
  #     ##  #### ####  #     #   #  #   #
  ####  # # #  # #  #  #     #####  #   #
  #     #   #### ####  #    #     # #   #
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3bf90) [0x7f206745af90]
FreeCAD/FreeCAD#1  0x7f2067f00b00 in QBackingStore::beginPaint(QRegion const&) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0xd0
FreeCAD/FreeCAD#2  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x174099) [0x7f2068574099]
FreeCAD/FreeCAD#3  0x7f20685a4fa8 in QWidget::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x468
FreeCAD/FreeCAD#4  0x7f2068562f5e in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x7e
FreeCAD/FreeCAD#5  0x7f2069c26388 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x88
FreeCAD/FreeCAD#6  0x7f20678b1718 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x118
FreeCAD/FreeCAD#7  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x175155) [0x7f2068575155]
FreeCAD/FreeCAD#8  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x177bc0) [0x7f2068577bc0]
FreeCAD/FreeCAD#9  0x7f206858ea80 in QWidget::repaint(QRect const&) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x80
FreeCAD/FreeCAD#10  0x7f206858eada in QWidget::repaint() from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x3a
FreeCAD/FreeCAD#11  0x7f2068711709 in QSplashScreen::repaint() from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x9
FreeCAD/FreeCAD#12  /usr/lib/freecad-python3/lib/libFreeCADGui.so(+0x773909) [0x7f2069f73909]
FreeCAD/FreeCAD#13  0x7f206971583d in Base::ConsoleSingleton::NotifyLog(char const*) from /usr/lib/freecad-python3/lib/libFreeCADBase.so+0xbd
FreeCAD/FreeCAD#14  0x7f2069715b13 in Base::ConsoleSingleton::Log(char const*, ...) from /usr/lib/freecad-python3/lib/libFreeCADBase.so+0x213
FreeCAD/FreeCAD#15  0x7f2069bbba81 in messageHandler(QtMsgType, QMessageLogContext const&, QString const&) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x51
FreeCAD/FreeCAD#16  /lib/x86_64-linux-gnu/libQt5Core.so.5(+0xc3ae0) [0x7f20676c3ae0]
FreeCAD/FreeCAD#17  /lib/x86_64-linux-gnu/libQt5Core.so.5(+0xc3bf8) [0x7f20676c3bf8]
FreeCAD/FreeCAD#18  0x7f206769051d in QMessageLogger::warning(char const*, ...) const from /lib/x86_64-linux-gnu/libQt5Core.so.5+0xaf
FreeCAD/FreeCAD#19  /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x615ba) [0x7f20618b55ba]
FreeCAD/FreeCAD#20  /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x62582) [0x7f20618b6582]
FreeCAD/FreeCAD#21  /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x643ab) [0x7f20618b83ab]
FreeCAD/FreeCAD#22  0x7f2067f00567 in QBackingStore::resize(QSize const&) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0xa7
FreeCAD/FreeCAD#23  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x17358f) [0x7f206857358f]
FreeCAD/FreeCAD#24  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x174a5a) [0x7f2068574a5a]
FreeCAD/FreeCAD#25  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1c116c) [0x7f20685c116c]
FreeCAD/FreeCAD#26  0x7f2068562f5e in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x7e
FreeCAD/FreeCAD#27  0x7f2069c26388 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x88
FreeCAD/FreeCAD#28  0x7f20678b1718 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x118
FreeCAD/FreeCAD#29  0x7f2067d3e73d in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0x8d
FreeCAD/FreeCAD#30  0x7f2067d11e1c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0xac
FreeCAD/FreeCAD#31  /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x6dc7a) [0x7f20618c1c7a]
FreeCAD/FreeCAD#32  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x299) [0x7f206591f7a9]
FreeCAD/FreeCAD#33  /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x54a38) [0x7f206591fa38]
FreeCAD/FreeCAD#34  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c) [0x7f206591facc]
FreeCAD/FreeCAD#35  0x7f20679094b6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x66
FreeCAD/FreeCAD#36  /usr/lib/freecad-python3/lib/libFreeCADGui.so(+0x773909) [0x7f2069f73909]
FreeCAD/FreeCAD#37  0x7f206971583d in Base::ConsoleSingleton::NotifyLog(char const*) from /usr/lib/freecad-python3/lib/libFreeCADBase.so+0xbd
FreeCAD/FreeCAD#38  0x7f2069715b13 in Base::ConsoleSingleton::Log(char const*, ...) from /usr/lib/freecad-python3/lib/libFreeCADBase.so+0x213
FreeCAD/FreeCAD#39  0x7f206971622a in Base::ConsoleSingleton::sPyLog(_object*, _object*) from /usr/lib/freecad-python3/lib/libFreeCADBase.so+0x6a
FreeCAD/FreeCAD#40  /lib/x86_64-linux-gnu/libpython3.10.so.1.0(+0x128413) [0x7f2068d28413]
FreeCAD/FreeCAD#41  /lib/x86_64-linux-gnu/libpython3.10.so.1.0(_PyObject_MakeTpCall+0x8e) [0x7f2068cdebce]
FreeCAD/FreeCAD#42  /lib/x86_64-linux-gnu/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x90fc) [0x7f2068c78cfc]
FreeCAD/FreeCAD#43  /lib/x86_64-linux-gnu/libpython3.10.so.1.0(+0x1c70c6) [0x7f2068dc70c6]
FreeCAD/FreeCAD#44  /lib/x86_64-linux-gnu/libpython3.10.so.1.0(PyEval_EvalCode+0xb9) [0x7f2068dc1b09]
FreeCAD/FreeCAD#45  /lib/x86_64-linux-gnu/libpython3.10.so.1.0(+0x211899) [0x7f2068e11899]
FreeCAD/FreeCAD#46  /lib/x86_64-linux-gnu/libpython3.10.so.1.0(PyRun_StringFlags+0x75) [0x7f2068e129a5]
FreeCAD/FreeCAD#47  0x7f206972b7a8 in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /usr/lib/freecad-python3/lib/libFreeCADBase.so+0x68
FreeCAD/FreeCAD#48  0x7f2069bbc0ff in Gui::Application::runInitGuiScript() from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x3f
FreeCAD/FreeCAD#49  0x7f2069bc1bd9 in Gui::Application::runApplication() from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x10c9
FreeCAD/FreeCAD#50  freecad(+0x4c01) [0x558ffef3cc01]
FreeCAD/FreeCAD#51  /lib/x86_64-linux-gnu/libc.so.6(+0x2718a) [0x7f206744618a]
FreeCAD/FreeCAD#52  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7f2067446245]
FreeCAD/FreeCAD#53  freecad(+0x5ad1) [0x558ffef3dad1]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
@luzpaz if I understood correctly this has been fixed in 0.21 right? in that case should we not add the corresponding "fixed for 0.21" tag for this issue so we close it when that's released and just remove this from the 0.21 project board?

**Comment by yorikvanhavre** [comment]
I understand it's the Qt version that's the problem, Qt5.15.7 crashes, Qt5.15.8 works.
On our side everything is okay then.. @kkremitzki it might be good to issue a 0.20.3 in Debian (Qt 5.15.8 is in unstable and testing already) when @donovaly is ready with his?

**Comment by adrianinsaval** [comment]
could this also be related to the multi monitor bug on windows where freecad fails to launch? do we have an issue for that bug?

**Comment by benj5378** [comment]
I'll just add these details
```
#95 0x00007ffff2cf7c1c in  () at /lib/x86_64-linux-gnu/libpython3.12.so.1.0
#96 0x00007ffff2cfb234 in PyRun_StringFlags () at /lib/x86_64-linux-gnu/libpython3.12.so.1.0
#97 0x00007ffff3790240 in Base::InterpreterSingleton::runString[abi:cxx11](char const*)
    (this=0x55555562c630, sCmd=0x7ffff6eaaba0 <FreeCADGuiInit> "#", '*' <repeats 75 times>, "\n#*   Copyright (c) 2002,2003 Jürgen Riegel <juergen.riegel@web.de>         *\n#*", ' ' <repeats 43 times>...)
    at /home/bensay/Development/FreeCAD/src/Base/Interpreter.cpp:249
#98 0x00007ffff645b590 in Gui::Application::runInitGuiScript() ()
    at /home/bensay/Development/FreeCAD/src/Gui/Application.cpp:1981
```
