### ISSUE TITLE
Workbench failure Draft - no module named Arch_rc 

### ISSUE THREAD

**Issue by Superbobo75** [FreeCAD/FreeCAD-Bundle#232]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37464 (Git)
Build type: Release
Branch: main
Hash: db48a78d5a545bb21a5c80a9fa4b4c983fbbe951
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Czech/Czech Republic (cs_CZ)
Installed mods: 
  * Assembly4 0.50.7
  * BIM 2021.12.0
  * Curves 0.6.23
  * fasteners 0.5.20
  * Gridfinity 0.3.0
  * Manipulator 1.5.7
  * ThreadProfile 1.89.0

When I try to switch to Draft - when Freecad is newly opened - the popup "Workbench failure - no module named Arch_rc " appears in the report view. :

15:36:57  No module named 'Arch_rc'Error: Initializing one or more of the Draft modules failed, Draft will not work as expected.
15:36:57  No module named 'Arch_rc'
15:36:57  Traceback (most recent call last):
  File "E:\FreeCAD_weekly-builds-37464-conda-Windows-x86_64-py311\Mod\Draft\InitGui.py", line 94, in Initialize
    self.drawing_commands = it.get_draft_drawing_commands()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FreeCAD_weekly-builds-37464-conda-Windows-x86_64-py311\Mod\Draft\draftutils\init_tools.py", line 42, in get_draft_drawing_commands
    from draftguitools import gui_arcs
  File "E:\FreeCAD_weekly-builds-37464-conda-Windows-x86_64-py311\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FreeCAD_weekly-builds-37464-conda-Windows-x86_64-py311\Mod\Draft\draftguitools\gui_arcs.py", line 37, in <module>
    import Draft
  File "E:\FreeCAD_weekly-builds-37464-conda-Windows-x86_64-py311\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FreeCAD_weekly-builds-37464-conda-Windows-x86_64-py311\Mod\Draft\Draft.py", line 53, in <module>
    from draftutils.utils import ARROW_TYPES as arrowtypes
  File "E:\FreeCAD_weekly-builds-37464-conda-Windows-x86_64-py311\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FreeCAD_weekly-builds-37464-conda-Windows-x86_64-py311\Mod\Draft\draftutils\utils.py", line 42, in <module>
    from draftutils import params
  File "E:\FreeCAD_weekly-builds-37464-conda-Windows-x86_64-py311\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FreeCAD_weekly-builds-37464-conda-Windows-x86_64-py311\Mod\Draft\draft

**Comment by maxwxyz** [comment]
can you manually remove the BIM addon and try again?
