### ISSUE TITLE
Using the Measure tool crashes FreeCAD...

### ISSUE THREAD

**Issue by CIKoolK** [FreeCAD/FreeCAD-Bundle#327]
I just found last evening that using the Measure tool crashes the last 3 or 4 builds on my Linux Mint v22 system (the last build that works is 38946:

1. Launch FC (I just used build 39092), open a new empty file;
2. Create a body;
3. Add a simple object (like a box;
4. Open the Measure tool;
5. Attempt to measure the length of any edge of the box;
6. FC crashes;
7. The last build that works is 38946, 1.0.0 RC2 (build 38806) works too.

Here's part of what I Get running it in a terminal session (I tried posting the entire thing is  64 lines (I.e A great TL;DR candidate):

```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x45320) [0x7c5151845320]
#1  0x7c5154dc2583 in Gui::DAG::Model::slotChangeObject(Gui::ViewProviderDocumentObject const&, App::Property const&) from /media/Applications/FreeCAD-39092/usr/bin/../lib/libFreeCADGui.so+0x163
#2  /media/Applications/FreeCAD-39092/usr/bin/../lib/libFreeCADGui.so(+0x50217c) [0x7c5154b0217c]
#3  0x7c5154b05517 in Gui::Document::slotChangedObject(App::DocumentObject const&, App::Property const&) from /media/Applications/FreeCAD-39092/usr/bin/../lib/libFreeCADGui.so+0x207
#4  /media/Applications/FreeCAD-39092/usr/bin/../lib/libFreeCADApp.so(+0x22a514) [0x7c5153a2a514]
#5  0x7c5153a65ef4 in App::DocumentObject::onChanged(App::Property const*) from /media/Applications/FreeCAD-39092/usr/bin/../lib/libFreeCADApp.so+0x134
#6  0x7c5153b83a65 in App::Property::hasSetValue() from /media/Applications/FreeCAD-39092/usr/bin/../lib/libFreeCADApp.so+0x135
#7  0x7c5153bf4da8 in App::PropertyString::setValue(char const*) from /media/Applications/FreeCAD-39092/usr/bin/../lib/libFreeCADApp.so+0x138
#8  0x7c513b5dac37 in MeasureGui::ViewProviderMeasureBase::updateData(App::Property const*) from /media/Applications/FreeCAD-39092/usr/lib/MeasureGui.so+0x547
#9  0x7c5154f879a1 in Gui::ViewProviderDocumentObject::updateView() from /media/Applications/FreeCAD-39092/usr/bin/../lib/libFreeCADGui.so+0x101
#10  0x7c5154b06465 in Gui::Document::slotNewObject(App::DocumentObject const&) from /media/Applications/FreeCAD-39092/usr/bin/../lib/libFreeCADGui.so

My system:
![Myconfig-10-02-2024](https://github.com/user-attachments/assets/a6ed3c12-63a3-422f-b756-a120552e257a)

I'm just getting ready to boot Win 10 Pro (which I REALLY do not like doing) to see how it goes there...

Did it:
The newest available  build for Windows was 39057, it worked as it should on Win 10 Pro--it (b39057) crashes as described above on my Linux system...
Damn, Windows is slow,,,

**Comment by adrianinsaval** [comment]
I can't reproduce this issue, does it happen when using freecad in [safe mode](https://wiki.freecad.org/Std_RestartInSafeMode)? Are you experiencing this in the appimage or in self compiled builds? can you check if the ppa version works?

please post your full version information (help>about>copy to clipboard)

> Here's part of what I Get running it in a terminal session (I tried posting the entire thing is 64 lines (I.e A great TL;DR candidate):

please post the full text too, it may be useful

I am not sure if this is truly a packaging problem so I'm going to move it to the main repo
