### ISSUE TITLE
Fem conflict with h5py?

### ISSUE THREAD

**Issue by arthurx70** [FreeCAD/FreeCAD-Bundle#66]
I tried to compile the 0.20 src code, run the FreeCAD.exe, after type in "import Fem" in python console, then type in "import h5py" in python console
`
>>>import Fem
>>>import h5py
>>>Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "H:\workspace\CAD\FreeCAD-master\Freecad_build\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "H:\workspace\CAD\FreeCAD-master\Freecad_build\bin\lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version
  File "H:\workspace\CAD\FreeCAD-master\Freecad_build\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "H:\workspace\CAD\FreeCAD-master\Freecad_build\bin\lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5
  File "H:\workspace\CAD\FreeCAD-master\Freecad_build\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "h5py\h5.pyx", line 1, in init h5py.h5
  File "H:\workspace\CAD\FreeCAD-master\Freecad_build\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: DLL load failed while importing defs: Can not find the specified program`

after type in "import h5py"  in python console, then  type in "import Fem" in python console
`
>>>import h5py
>>>import Fem
>>>Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "H:\workspace\CAD\FreeCAD-master\Freecad_build\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: DLL load failed while importing Fem: Can not find the specified program`

why? 
how to fix it?

**Comment by adrianinsaval** [comment]
I doubt this issue is still relevant but even if it is this is not the place to ask this. This repo is about packaging of the application. If still interested I suggest going to the forum about this
