### ISSUE TITLE
FreeCAD v0.19.2 is crashed

### ISSUE THREAD

**Issue by liubog2008** [FreeCAD/FreeCAD-Bundle#81]
I use appimage https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/0.19.2/FreeCAD_0.19-24291-Linux-Conda_glibc2.12-x86_64.AppImage
```
FreeCAD 0.19, Libs: 0.19R24291 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2021
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####
  #                    #      # #   #   #
  #     ##  #### ####  #     #   #  #   #
  ####  # # #  # #  #  #     #####  #   #
  #     #   #### ####  #    #     # #   #
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

<Import> ImportOCAF2.cpp(541): free shape count 496
<Import> ImportOCAF2.cpp(330): \X2\91D15C5E4EF6\X0\ (4) has empty shape
<Import> ImportOCAF2.cpp(330): Metal LED Illuminated Latching 16mm Power Push Button ON-OFF Switch 12V (2) has empty shape
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3cf80) [0x7f2f58559f80]
#1  0x7f2f5a3388fc in App::DocumentObject::getNameInDocument() const from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADApp.so+0xc
#2  0x7f2f5afdc404 in Gui::DocumentItem::getViewProvider(App::DocumentObject*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADGui.so+0x34
#3  0x7f2f5afe61ff in Gui::TreeWidget::_slotDeleteObject(Gui::ViewProviderDocumentObject const&, Gui::DocumentItem*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADGui.so+0x23f
#4  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADGui.so(+0x419837) [0x7f2f5ad91837]
#5  0x7f2f5addf76b in Gui::Document::slotDeletedObject(App::DocumentObject const&) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADGui.so+0x17b
#6  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADApp.so(+0x1f20d7) [0x7f2f5a3140d7]
#7  0x7f2f5a327478 in App::Document::removeObject(char const*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADApp.so+0xe8
#8  0x7f2ec02b71c0 in Import::ImportOCAF2::loadShapes() from /tmp/.mount_freecaCtUjW9/usr/lib/./Import.so+0xba0
#9  /tmp/.mount_freecaCtUjW9/usr/lib/ImportGui.so(+0x2030a) [0x7f2ee7d6a30a]
#10  /tmp/.mount_freecaCtUjW9/usr/lib/ImportGui.so(+0x1695b) [0x7f2ee7d6095b]
#11  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADBase.so(method_keyword_call_handler+0x374) [0x7f2f59ff3074]
#12  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(PyCFunction_Call+0x66) [0x7f2f5a789696]
#13  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(_PyObject_MakeTpCall+0x230) [0x7f2f5a731550]
#14  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x4ddd) [0x7f2f5a79b28d]
#15  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(_PyEval_EvalCodeWithName+0x2ea) [0x7f2f5a732d9a]
#16  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(PyEval_EvalCodeEx+0x3a) [0x7f2f5a7c040a]
#17  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(PyEval_EvalCode+0x1c) [0x7f2f5a7c042c]
#18  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(+0x1e05aa) [0x7f2f5a7e55aa]
#19  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(+0x224225) [0x7f2f5a829225]
#20  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(PyRun_StringFlags+0x80) [0x7f2f5a8292c0]
#21  0x7f2f5a0262cc in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADBase.so+0x6c
#22  0x7f2f5ae40091 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADGui.so+0x91
#23  0x7f2f5ae40231 in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADGui.so+0x101
#24  0x7f2f5ad768d7 in Gui::Application::open(char const*, char const*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADGui.so+0x197
#25  0x7f2f5ad9c8c4 in Gui::Application::sLoadFile(_object*, _object*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADGui.so+0x154
#26  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(PyCFunction_Call+0xf5) [0x7f2f5a789725]
#27  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(_PyObject_MakeTpCall+0x230) [0x7f2f5a731550]
#28  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x4ddd) [0x7f2f5a79b28d]
#29  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(_PyEval_EvalCodeWithName+0x2ea) [0x7f2f5a732d9a]
#30  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(PyEval_EvalCodeEx+0x3a) [0x7f2f5a7c040a]
#31  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(PyEval_EvalCode+0x1c) [0x7f2f5a7c042c]
#32  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(+0x1e05aa) [0x7f2f5a7e55aa]
#33  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(+0x224225) [0x7f2f5a829225]
#34  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(PyRun_StringFlags+0x80) [0x7f2f5a8292c0]
#35  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(+0x2246dd) [0x7f2f5a8296dd]
#36  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(+0x13507e) [0x7f2f5a73a07e]
#37  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x392) [0x7f2f5a796842]
#38  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(_PyEval_EvalCodeWithName+0x2ea) [0x7f2f5a732d9a]
#39  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(PyEval_EvalCodeEx+0x3a) [0x7f2f5a7c040a]
#40  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(PyEval_EvalCode+0x1c) [0x7f2f5a7c042c]
#41  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(+0x1e05aa) [0x7f2f5a7e55aa]
#42  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(+0x224225) [0x7f2f5a829225]
#43  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libpython3.8.so.1.0(PyRun_StringFlags+0x80) [0x7f2f5a8292c0]
#44  0x7f2f5a0262cc in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADBase.so+0x6c
#45  0x7f2f5ae40091 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADGui.so+0x91
#46  0x7f2f5ae40231 in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADGui.so+0x101
#47  0x7f2f2c25cdf6 in WebGui::BrowserView::urlFilter(QUrl const&) from /tmp/.mount_freecaCtUjW9/usr/lib/WebGui.so+0x536
#48  /tmp/.mount_freecaCtUjW9/usr/lib/WebGui.so(+0x25c48) [0x7f2f2c25ec48]
#49  0x7f2f58a4d594 in QObject::event(QEvent*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libQt5Core.so.5+0xbc
#50  0x7f2f5928a07f in QWidget::event(QEvent*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libQt5Widgets.so.5+0xcc5
#51  0x7f2f5933434f in QMainWindow::event(QEvent*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libQt5Widgets.so.5+0xdd
#52  0x7f2f5925e7f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libQt5Widgets.so.5+0xdc
#53  0x7f2f5926431d in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libQt5Widgets.so.5+0x1ac9
#54  0x7f2f5ae0edf9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADGui.so+0x89
#55  0x7f2f58a38606 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libQt5Core.so.5+0x86
#56  0x7f2f58a3883e in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libQt5Core.so.5+0x1da
#57  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libQt5Core.so.5(+0x1dc54c) [0x7f2f58a6754c]
#58  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7f2f559b523d]
#59  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/./libglib-2.0.so.0(+0x554d1) [0x7f2f559b54d1]
#60  /tmp/.mount_freecaCtUjW9/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x31) [0x7f2f559b5571]
#61  0x7f2f58a670e8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libQt5Core.so.5+0x5e
#62  0x7f2f58a35019 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libQt5Core.so.5+0x187
#63  0x7f2f58a38e8f in QCoreApplication::exec() from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libQt5Core.so.5+0xfd
#64  0x7f2f5ad98926 in Gui::Application::runApplication() from /tmp/.mount_freecaCtUjW9/usr/bin/../lib/libFreeCADGui.so+0x15f6
#65  /tmp/.mount_freecaCtUjW9/usr/bin/freecad(+0x44bf) [0x55eee00154bf]
#66  /usr/lib/libc.so.6(__libc_start_main+0xd5) [0x7f2f58544b25]
#67  /tmp/.mount_freecaCtUjW9/usr/bin/freecad(+0x47d9) [0x55eee00157d9]
```

**Comment by chennes** [comment]
Hello @liubog2008 -- you'll want to post your issue (with your complete FreeCAD version details, and in this case the file that's crashing the program, to the FreeCAD Forums: https://forum.freecadweb.org/viewforum.php?f=3

This
