### ISSUE TITLE
Trace back

### ISSUE THREAD

**Issue by koebis** [FreeCAD/FreeCAD-Bundle#91]
Hi, I am not shure is this the right place. If not pls let me know.
FreeCad version 0.20 27399 (22/02/04)

18:01:11  Traceback (most recent call last):
  File "<string>", line 23, in <module>
  File "<string>", line 18, in __init__
  File "<string>", line 7, in __init__
  File "C:\Program Files\FreeCAD 0.20\Mod\Start\StartPage\StartPage.py", line 304, in handle
    with open(html_filename, 'r') as f:
<class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'C:/Users/jakob/Documents/FCAD_zeichnungen/uebung1.FCStd'
18:01:11  [Errno 2] No such file or directory: 'C:/Users/jakob/Documents/FCAD_zeichnungen/uebung1.FCStd'

**Comment by luzpaz** [comment]
Please open a thread in the forum.freecad.org  
Thanks
